module.exports = {
  discordBotToken: process.env.DISCORD_BOT_TOKEN,
  discordClientID: process.env.DISCORD_CLIENT_ID,
  discordClientSecret: process.env.DISCORD_CLIENT_SECRET,
  discordRedirectURI: process.env.DISCORD_REDIRECT_URI,
  discordTestGuildID: process.env.DISCORD_TEST_GUILD_ID,
  encryptionSecret: process.env.ENCRYPTION_SECRET,
  mongoConnectionString: process.env.MONGO_CONNECTION_STRING,
  topGGToken: process.env.TOP_GG_TOKEN,
  teamMembers: process.env.TEAM_MEMBERS,
  s3BucketName: process.env.S3_BUCKET_NAME,
  awsAccessKeyId: process.env.AWS_ACCESS_KEY_ID,
  awsSecretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  betaTesters: process.env.BETA_TESTERS,
  betaGuilds: process.env.BETA_GUILDS,
  bunnyAPIKey: process.env.BUNNY_API_KEY,
};
